<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2008-04-02:/2008/04/keep-me-going-this-week"; ?>
		<div class="publishedentry">
			<h2>Keep me going this week</h2>
			<h3>02 April 2008  @ 14:57</h3>
			<p>I wanted to go to the gym last night, but instead I sat in my apartment and played with my joints. I was just messing around by standing on different parts of my feet and pushing against my ankles. In the process I discovered that there’s a blockage in the left ankle near the fibular articulation. As I walk around the office today I notice a similar tension in the right ankle in the same area. Weirdly, I can turn my left foot outward, laterally, and induce the feeling of the blockage, but no matter how much I turn the right ankle outward, I feel nothing unusual. I hope that this Friday, or SOON, Dr. Rugg can get those blockages out. I’ll continue to stretch and move them around.</p><p>Of course I need to strengthen all the surrounding muscles so that the changes stick.</p><p>Also last night I tried stretching my left big toe outward and upward, trying to loosen up the tendon that was insulted by surgery, and found that it kept popping every time I did that. I could even see the skin dipping into the space in the joint whenever I stretched the toe out. Neat and weirdly reminiscent of play-doh. </p><p>It was too cold and gloomy yesterday to incite a visit to the gym. Plus it’s such a cold, uninviting environment compared to the stoic softness of my apartment. Perhaps today I will be able to leave sooner, go to the gym and return with enough time to enjoy my austere confines.</p><p>Which is interesting. A month or so ago I wondered how long it would be until I felt more comfortable in my apartment than anywhere else. I think I’ve reached that point and now I want to wreck it. I think I’ll reconfigure. I don’t want to throw anything away unless I am sure it can’t be used for anything else.</p><p>Man I’m so excited to meet with Ian this Sunday. It’s going to be awesome. I don’t know what we’ll do exactly, but probably just meet up and talk about things. I have so many questions! I want to know what it’s like becoming a tenured professor, what he thinks I should study based on what I like, whether there’s hope for me in IT (even though I’m not at all drawn to it), what life is like as a professor, lots of things. I want to tell him about my work and this company and all the little things that annoy or interest me.</p><p>Yay! This thought will keep me going this week. Also this weekend I hope to go to the Field Museum at last. Tomorrow I have a dental cleaning, Friday is Dr. Rugg and Sharon, Saturday might be the museum, and Sunday is Ian! Yay!</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>