<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2007-07-29:/2007/07/emotional-diagramming"; ?>
		<div class="publishedentry">
			<h2>Emotional Diagramming</h2>
			<h3>29 July 2007  @ 20:49</h3>
			<p>I can't open up about this as easily. I also don't think most people would care to read about this, but I still want to make it a part of this blog. </p><p>Here is the diagram I made. I just mocked it up on the computer, though I originally had drawn it out by hand. <br /><a href="http://iam.solostyle.net/img/640/ed.jpg"><img src="http://iam.solostyle.net/img/320/ed_small.jpg" /></a></p><p>When something points to something else, it means it is because of or contains that something else. So I perceive my bitterness to be composed of comparison to my old self and others, resentment, no acceptance, and greed. Etc. I think my resentment is only a defense mechanism for a fear of people or intimacy or dependency or whatever that is. </p><p>It would take a long time to explain all of it, actually. I think I'm probably the only person who could understand that diagram, what I mean by those words. The blue words are the things I thought were the major issues when I started. The red is what all the big issues point to, which makes me curious about it. Not sure what to do about it.</p><p>For a long time now, I've kept saying to Nick and others that "this is not me" or "this is not really who I am, I usually don't care about these things" or "this is just temporary." I think it is just temporary, but it isn't "not" me. (I hate it when Nick uses double negatives, but I use them all the time myself, and they work way better than positives.)</p><p>Acceptance is probably the key to ending everything. But not just acceptance of my life and my situation. All these things are entities in me because they always have been. Nothing comes from nothing. There were probably seeds somewhere in me, or maybe they were actually big issues all along but nothing ever made them so prominent.</p><p>It's going to be hard to accept that they were always in me, but that might be the way to get myself to accept it all at once, once and for all. </p><p>I finally can't avoid the issues anymore. Does that mean I have to resolve them now? Is it a chance for me to step up and take it on instead of running away? Am I running away? Maybe by saying "this is not me" I am running away. Okay. This is not temporary. It's been around long enough. But I thought it was temporary in the beginning, and I'm going to make it temporary... by working on it until it dissolves away. </p><p>I'll try to see what I can do about acceptance. Every time I feel like complaining about something, I will try to accept it instead. I'm not sure how to do that? Does that mean when I feel pain in my foot, I think, "no no, this isn't not me, it's me. i'm feeling it, it's in my body. my foot is fucked. i am not a perfect physical body. i have pain. this is my pain. it hurts. swallow and smile"?</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>