<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-06-20:/2006/06/explosions-in-my-amygdala"; ?>
		<div class="publishedentry">
			<h2>Explosions in my amygdala</h2>
			<h3>20 June 2006  @ 21:49</h3>
			<p><p>I've been on the verge of tears for the past few weeks, I think. In Houston I would cry thinking about how crazy it felt now to be alive, and I sometimes felt I should be dead. Then that turned into actually feeling dead. Now it's pieces of those previous feelings plus the readiness to cry at anything for anything, to feel so deeply all the time because of this open wound.</p><br /><p>Although it doesn't matter so much whether or not I feel dead, I still feel so close to death. Ian told me today about Scott Hoover, this IT guy I remember helping me with my computer last summer in the CS department. He got hit by a car on his motorcycle and didn't go to the hospital. He went home, instead, and called all his friends to tell them what happened, all of whom told him to go to the hospital. He said he felt fine. Then a friend called the ambulance for him and had him taken to the hospital, but Scott died in the ambulance. I started crying when he told me about it. I apologized but Ian told me a story about himself. After he separated and divorced from his wife, for a long time anything that had even the tiniest degree of pathos would make him burst into tears. I can't imagine Ian crying, but I know he does feel a lot. He's an INTP (haha, right). It's true, I think I'm a little bit like that now. I'm glad that he told me that. He said the trauma is not what happened during the event but how it affects you after the event. Of course. But you don't know that when you're actually experiencing the trauma. In your everyday moments, you just assume that you'll get over it day by day. I've noticed that I'm much more <a href="http://www.auracolors.com/test.htm">blue</a> than I used to be. In fact, I wasn't even a smidgen of blue before, maybe just a 2 or a 3. Without doing the aura colors test I already sense that I am bluer than before.</p><br /><p>Anyway. What else have I noticed. Ah yes. I understand now those people who don't want to do anything. I empathize with complete laziness. I also empathize with giving up. And falling into bad habits. And self-destructive behavior. *Sigh* Yes. It's a good thing. This reminds me of that old nostalgic depression of my early adolescence. But I think I've learned something between then and now. Or maybe I have learned nothing; only my soul is awakened to pain and therefore tougher. What kind of learning is that? And how tough am I really if I'm so sensitive inside? It's all meaningless.</p><br /><p>I wonder if people who are "naturally" blue are just extremely empathetic and very close to trauma. Maybe they experienced something intense in their previous lives that has stayed with them until this life and that's why they can't control their emotions. SOmetimes I think I just want to die because I can't stand it.</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>