<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-06-27:/2006/06/two-months-left"; ?>
		<div class="publishedentry">
			<h2>Two months left</h2>
			<h3>27 June 2006  @ 12:14</h3>
			<p><p>I'm freaked out. I have no idea if I will actually be able to do this triathlon. Swimming is the thing that suffered the most during the earlier part of rehab. I haven't done open-water swimming yet, but I just know that it will be completely different. No resting, no breaks, and a horde of people all splashing around. I wish I could do a race between now and the triathlon. I wouldn't mind just a swim race.</p><br /><p>If I take a good break starting a few days before the tri, I should be able to run. I'm not worried about biking. The transitions between the sets--that's where I might lose my cool. I just have to be as safe and calm as possible.</p><br /><p>I considered joining a triathlete club to get better training. I saw this on the <a href="http://www.togetherwetri.com/discuss/#11">Chicago Triathlon Club website</a>.</p><br /><blockquote><em>How many days a week do I need to train?</em><br /><br />A minimum of 4 days a week. Giving your weakest sport 2 days of focus and your 2 stronger sports one day a week. Building on all with increasing intensity and endurance, but allowing rest days and tapers in between your intense weeks is the best way to train. We always stress that more often than not less is more. You must always listen to your body while training. The most common schedule however is a 5-day a week training schedule. With 2 days a week on your 2 weakest sports and 1 day a week on what you consider your strength. Many seasoned athletes train 6 days a week and 1 rest day. But this intensity is not needed for most people.<br /></blockquote><br /><p>So I should be swimming 2x a week, running 2x a week, and biking once a week. Currently I bike 3 or 4 times a week, run once or twice, and swim once or twice. I've also been doing two or more sports a day. Today I biked and swam, but did not do either very intensely because I needed to get some strength training in as well.</p><br /><p>My leg is not completely back to normal, so the type of training described on that site is probably not possible for me. A better training schedule would be something like this:</p><br /><ul><br /><li><em>Day 1:</em> Endurance swim ~1000m</li><br /><li><em>Day 2:</em> Endurance run ~4-5mi + Moderate endurance bike ~20-40mi</li><br /><li><em>Day 3:</em> Endurance bike ~50-60mi + Strength training + Qi Gong</li><br /><li><em>Day 4:</em> Restful rest: meditation, stretching, Qi Gong</li><br /><li><em>Day 5:</em> Endurance swim ~500m + Sprint swim ~6x 25m or 50m</li><br /><li><em>Day 6:</em> Sprint run and hills ~2-3mi + Fast endurance bike ~20-30mi</li><br /><li><em>Day 7:</em> Active rest: Light cardio + Strength training + Qi Gong</li><br /></ul><br /><p>Hmm.. Does this seem feasible? I wish I had a coach. I'd like some input and feedback from people who have done it. I don't want to just hope that it all works out. I want to make every effort to make it happen.</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>