<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2007-01-15:/2007/01/recovery-restart"; ?>
		<div class="publishedentry">
			<h2>Recovery restart</h2>
			<h3>15 January 2007  @ 15:14</h3>
			<p>Throughout the past year, recovery has taken a variety of forms and each form has had its own set of phases. But the strange thing is that recovery from an injury like this one isn't limited to the catastrophe and its aftermath. Life continues and builds on itself. Events are situated in the context of a life, so my recovery inevitably unearthed and intensified existing physical and psychological developments.</p><p>All this leads to confusion about how long recovery takes and the status of progress over time. The idea of keeping a blog is so that I don't have to rely on memory, and so that I'm discouraged from rewriting my own history. The facts of each day should speak for themselves. So I thought I was nearing the end of this recovery period, but it looks like yet another new phase has begun.</p><p>Despite my desire not to rewrite my own history, I feel it necessary to make sense and recap the past from the perspective of this moment. I realize the flaws in doing this, but at least I'm being clear about it.</p><p>So, February - August 2006 was a time of heightened energy and determination. A gushing of desire and love of life. June - August was difficult emotionally and psychologically because I had little social support, but compared to what transpired shortly after, it was actually pretty positive.</p><p>Following that, I started back in school, exercising as much as possible to keep in line with the physical recovery. September - December 2006 was a period of great strife and striving. Medical appointments, declining physical and mental health, and surprising uncontrollable emotional breakdowns peppered those months.</p><p>Transition period at the end of the year. The last weeks of December were far less painful than the previous months, emotionally and physically.</p><p>At the start of this year, I found myself struggling physically again, which influenced (inevitably) the psychological adjustment of the Chicago situation. Not only that but major life decisions and liminalism bring with them a whole host of mental disarray.</p><p>As I said in my last post, I need help. But no one is going to help me but myself. So I'm on a mission now to make this happen. I talk to different people about future life plans, what sounds feasible, what their experiences have been. I'm also meeting with different personal fitness trainers for ideas on strengthening the body despite the continuing pain. I read a lot of books and websites about personal relationships and interactions to help me socially. It's all necessary. I realize that seeking guidance does not preclude independence and self-assertion. I still use this mind and heart to make sense of everything.</p><p>Ultimately, I still need to write about each day, every day. It isn't for idle public display, but making it public somehow heightens the public responsibility, makes me feel more accountable for my words, enforces clarity and truthiness (copyright Stephen Colbert).</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>