<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-04-05:/2006/04/im-a-machine"; ?>
		<div class="publishedentry">
			<h2>I'm a Machine</h2>
			<h3>21 October 2007  @ 19:10</h3>
			<p><p>My lord, I've been wanting to write everyday in this blog for the past week, but I've had to force myself not to because I feel like I had offended a friend of mine who was reading this. But it seems I've gotten more readers now and I can't let them down! And I still have much to say.</p><br /><p>So far, this week has opened my eyes more than any other time during my recovery. The progress is unbelievable--similar to the kind of growth you see in newborns and toddlers. (And according to my parents, I am "reborn".)</p><br /><h3>Adrenaline sea</h3><br /><p>Since I joined the <a href="http://www.ymcahouston.org/CGI-BIN/LANSAWEB?WEBEVENT+L0B4AE1439272D19C6593421+PRD+ENG">Fort Bend YMCA</a> on April 1, I've been going every day without fail. It started with a sputter, as Saturday's power cycle class wrenched free intense, long-blocked energy that fried my muscles, making Sunday's workout little more than sitting meditation. But since Monday, the power cycle class has gotten more intense and beneficial to decreasing the pain in my leg. I feel fluid after the class, as if nothing ever happened. The classes are meant for those who are training for the <a href="http://www.ms150.org/ms150/">MS 150</a>, but of course anyone is welcome. That means the workouts vary with hill-climbing routines at increasing resistance, drills, and interval sprints. The hill-climbing and runs require getting off the saddle and either staying upright using your abs or hovering over the saddle as low as possible. I couldn't even dream to attempt those two days ago. But yesterday and today, I not only got out of the saddle (grudgingly at first), but I'm now using the right leg almost as much as the left.</p><br /><p>Today the fellow in the bike behind me said after class, "This girl never sweats, never gets tired. It's demoralizing!" Of course he was joking, because I was dripping and my bike was slippery. But that was so nice to hear! I think he meant "It's so inspiring!" because he was smiling. Then I saw him crunching away at the ab class immediately after. That session is led by a drill sargeant who turns every one of those fifteen minutes into hell. I loved it, and I loved seeing everyone try their best. The people at the YMCA work hard, encourage each other, and have positive attitudes. I'm so glad I joined!</p><br /><p>I also attended my first master swim class, led by a master swimmer of 12 years named Tish. The classes are every Tuesday and Thursday from 5:30-6:30 AM and only $25 a month! I tried it out, as I've never been on a swim team, never been coached, and never had the experience of doing drills with other people. We did one-armed laps, kicked with flippers (or fins), and did all kinds of things new to me. By the time the triathlon comes around, I'll be in tip-top shape!</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>