<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2007-03-11:/2007/03/strings-and-flowers"; ?>
		<div class="publishedentry">
			<h2>Strings and flowers</h2>
			<h3>11 March 2007  @ 18:54</h3>
			<p>This weekend was the beginning of many new things. I rediscovered my love for drawing, I opened up my mind to a new world of drumming, and I bought a guitar to help open up an even wider musical world vocally and melodically. It was also my personal official start of a new season. Tonight my parents and I bought flowers and dirt. We created new platforms around the two front trees in which to bed the flowers. Tomorrow morning I will plant the flowers.</p><p>After signing up for drumming lessons I went to my first one yesterday. I didn't know what exactly to expect--a critique of my poor technique and form was among the things I considered. My instructor is Patrick Courtney (at the <a href="http://percussiononline.com/lessons.html">Percussion Center</a>), also a left-hander like me. He plays traditional grip mostly, it seems. I started out playing a basic back-beat with a bit of a twist and tried to do a fill.. didn't really work. I was a bit nervous. Pat took that opportunity to jump in and show me the idea behind fills. People just play whatever they feel like--that's how fills get "composed." It's like writing a letter to a friend, he says. You may not like that sentence, so you try again. I was surprised but I felt more open and experimental after the lesson.</p><p>Technique was not the least of my problems.. I expressed my desire to play rolls, and he gave me some exercises to work on. I had been doing them already, but now I'm doing them every chance I get... while driving, thinking, sitting around. Whenever.</p><p>Now I have another toy, the guitar. It's an Epiphone PR-150 (Acoustic) with an on-board pickup that was sold to me by a dude in the city. He got the bridge saddle shaved down, too, which means the strings are closer to the fretboard, making it easier to press down. It's great weather outside.. I sat out there with the flowers and explored the relationships between the strings.</p><p>I've been trying to give my feet a break, but they hurt so easily. I only moved dirt around today and that alone made them start aching. Hopefully with my new toys, I won't feel like I've let my desires and dreams slip away. I can't bike or walk (or run) or play hacky sack or do gymnastics anymore, but I can sit (depending on the seat) and play an instrument (drums, guitar), or sit and draw (or paint).</p><p>I guess life just kinda happens. The energy that fuels it is always swirling around. You can allow yourself to get swirled around with it, and you can sometimes be so lucky as to direct it. Maybe I was more on the directing side today. I did take my chances, so I can't say I was swirling around in perfect harmony, but I think it all worked out in the end.</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>