<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-03-30:/2006/03/physical-status-update"; ?>
		<div class="publishedentry">
			<h2>Physical Status Update</h2>
			<h3>21 October 2007  @ 19:10</h3>
			<p><p>Today saw the removal of those annoying elastic bands around the <a href="http://catalog.nucleusinc.com/enlargeexhibit.php?ID=2442">arch bars</a>. I opted to have the arch bar removal procedure done tomorrow late morning. Little did I know, until today, that the arch bars contain little wires that go <em>into</em> the gums and wrap around each tooth. Removal requires being sedated and locally anesthetized. Sedation requires no intake of food or liquid eight hours prior to the procedure. Since I'm always ravenous, wish me luck in my attempt to stay awake until two in order to consume vast amounts of food.</p><p>Great. Another procedure that requires anesthesia. I wonder how many it takes before the drugs don't affect me anymore. Or whether I might become allergic to them at some point.</p><p>The mouth opens! But not very wide. I will be using my fingers to pry my jaws apart as much as I can today. In my fear of starvation tomorrow morning, I have started eating solidish food. I had a peanut butter sandwich that took me forty minutes to complete. I wanted to eat raw broccoli, or at least lightly steamed brocolli, but alas... </p><p>Because the manibular break right in the center of my jaw was so clean and deep, it will take a solid six months for the new bone formation to harden. Dr. Brotherton, DDS, MD, advised that I stay away from eating anything that makes noise when I chew for the next six months.</p><p>Six months.</p><p>Therefore, I'm having a party on October 1, 2006. Everyone in the world is invited. I don't even care who pops in on it. Because I'll be eating raw broccoli. And parsnips. (And, goddammit, ROCKS.)</p><p>Tomorrow will be another sucky day, my mouth full of blood and gauze, and ice applied to my face for the following 48 hours.</p><p>Numbness update! My lower lip is still numb. There are two main nerves that run along each side of the lower jaw and stop well before the center of the jaw. They are the <a href="http://en.wikipedia.org/wiki/Image:Gray782.png">mandibular nerves</a> (one on either side). These did not get cut during surgery, so I did not lose permanent feeling in the lip or jaw. If there had been any damage, I will find out a year from now if the feeling still has not returned. The numbness I feel now is from the minor nerves that probably got cut during surgery, and these grow back about one millimeter a day.</p><p>Before, most of my foot and ankle was numb, especially the top part and the lateral side. The feeling has started to come back as the swelling has decreased. There is very slight swelling remaining in the ankle, and the ankle and area just above the ankle are always a bit cool, while the knee is always warm. I think once I start walking, the circulation will improve.</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>