<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-03-03:/2006/03/positive-vibes-always"; ?>
		<div class="publishedentry">
			<h2> Positive Vibes Always</h2>
			<h3>21 October 2007  @ 19:01</h3>
			<p><p class="post"></p><div style="clear: both;"></div><div class="vitals"><h1>Vitals</h1><div class="bp"><h1>BP</h1><p>??/??</p></div><div class="temp"><h1>Temp</h1><p>??</p></div></div><div class="clear">&nbsp;</div><p class="vitalspost">I don't know my vitals because they took them this morning while I was asleep. I was so out of it that I could barely move my arm for the blood pressure test.</p><br /><p>NEWS! The Daily Northwestern spit out another article about my incident:</p></p><p><blockquote><br />Police will use list to find Hummer's mystery driver</p><p>by Beth Murtagh and Laura Olson</p><p>March 03, 2006</p><p>Evanston Police Department officials received a list of registered Hummer H2's in Illinois within the last week to aid the search for the driver of the yellow Hummer that struck a Weinberg senior in February.</p><p>"We're looking at that information and trying to put it into usable form," said Deputy Chief Joe Bellino of EPD. "It's quite extensive."</p><p>Bellino declined to say how many vehicles were on the list, which was compiled by the Illinois Secretary of State's office.</p><p>An unidentified driver ran a stop sign at the Lake Street and Sherman Avenue on Feb. 16 and struck bicyclist Archana Sriram. The driver then drove away. There is no description of the driver.</p><p>Sriram suffered fractures to her leg, jaw, pelvic area and face, and she will undergo three months of physical therapy before walking again.</p><p>The Chicagoland Bicycle Federation held an event at the accident's scene Feb. 24. EPD Chief Frank Kaminski and Evanston Bicycle Club President Neal Ney were among the speakers at the event, which promoted a Chicagoland Bicycle Federation campaign meant to curb aggressive driving.</p><p>EPD asks that people who might have information pertaining to the investigation call (847) 866-5000.</p><p>— Beth Murtagh and Laura Olson<br /></blockquote></p><p><p>Still nothing has really turned up. I don't doubt that criminal fled to some other state by now. He probably got his damages repaired at a no-name body shop, or repainted it, or changed the license plate by now. There's no telling. He has no conscience or care for human beings. I know he knows he hit me. He <span style="font-style: italic;">sped away</span>.</p><br /><p>Anyway, I don't have the <a href="http://iam.solostyle.net/">energy</a> to be angry. All the energy I have must go toward healing and joy. Most of the time I sit here in this hospital not feeling much of anything emotionally, but sometimes it occurs to me that I'm only here for another week, then I'm going home to Houston, and  the healing process will continue but will always be new and exciting. The hardest experiences end up being the best.</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>