<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-03-04:/2006/03/sunshine"; ?>
		<div class="publishedentry">
			<h2>Sunshine</h2>
			<h3>21 October 2007  @ 19:01</h3>
			<p><p class="post"><div style="clear:both;"></div><p>My friends are taking me out today! In just a few minutes they'll be here to steal me into the wintry sunshine to frolick one-legged with nature and civilization. I visited Ruth last night and we just chatted about things. She's great to talk to. I've asked Kevin to bring flowers when he gets here so that I can give them to her (with a note). I also met Ethel last night, who is staying in the next room. She was wonderful to talk to, as well. We talked about mothers and love and growing up.</p><br /><p>I want to radiate joy and love for everyone here! I don't need their healing energy, but I'll sure take what comes. I have my own inner power to heal and I just want to make sure everyone else is moving forward and looking up, as well.</p><br /><p>This morning's therapy was great. I'm going to miss the afternoon therapy because I'm going out, but I'll do some at Kevin's place or something. Today I asked for dumbbells to keep my arms toned. I usually do 20 lb. curls but I told them to give me 10 lbs. bells and they hesitated to give me even that much. So I didn't really get tired. They made me crutch a lap around the floor, but that was also nothing. They just really underestimate my stamina and strength. I look like a little skinny nothing, but I have the power of someone much larger.</p><br /><p>Well I'll just try crutching around as much as possible while I'm hanging out with my lovely friends. I'm going to meet two new people today, Courtney and Ken, both of whom are Kevin's friends from college in Detroit. But most of all I want to see Kevin's family again. They're such great, fun people. We might even stop by my apartment--what a trip that will be! I haven't been <span style="font-style:italic;">home</span> in so long. I might start crying.</p><br /><p>Master Choi called twice this morning and I returned his call. Unfortunately the reception wasn't great, but I got to tell him what I wanted. The intense martial art training that he put me through, that he ingrained in me to do on my own, that I continue to strive to do even now, has given me the ability to pull through any physical and spiritual pain. I feel so strong that sometimes I think Life is kind of stupid for having done this to me. I'm already positive, strong-willed, and work hard, so this experience isn't teaching me that. I suppose one thing I am learning is to be kind to other people who are suffering, like Ruth and other patients here. i'm learning how to talk to people and how to accept them. I'm also learning how to relax and do nothing (which I generally don't do). And the cherry on top would be that life is more interesting and fun when you have to find new ways to do what you've always done.</p><br /><p>Lunch is here, and I have to make a trip to the bathroom (fun!). My friends should be here soon! Spread the love!</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>