<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2008-07-23:/2008/07/and-now-about-the-job"; ?>
		<div class="publishedentry">
			<h2>And now, about the job</h2>
			<h3>23 July 2008  @ 06:42</h3>
			<p>I love having the opportunity to do good work. (But when have I ever not had the opportunity to do good work? Isn't it always possible?) Oddly, I think something my horoscope says applies pretty well to what's been going on now: </p><p><blockquote>This is a time of balance and order in your life. You may have to work hard for financial gain, but at least your affairs are in order. Your business or professional life is well organized, and you should be making steady progress toward your goals. The gains you make at this time are not strokes of luck, they are the solid results of good organization. -Astrodienst</blockquote></p><p><em>Solid results of good organization.</em> I agree. Even though this is mostly about my work life, I think it applies even more readily to my health life. Man, I am just really always thinking about that, huh? I can't even focus on talking about just my job. My internal work is so much more compelling. Like this morning, instead of going to Master Swim and having to flail around in a crowded pool (now that all the Courts Plus members are going to the outdoor pool because of construction at Courts Plus), I hung out on my balcony and pushed my internal organs around. I think it helps. It's something Sharon taught me that I can sort of do to myself now. ANYWAY, my point is ... my health improvement is not a result of luck, it's a result of hard work.</p><p>Am I really making professional gains that result from good organization? I'm still too myopic to see whether I am making professional gains. There have been moments of success here and there for which I have been recognized. But work goes on... We don't stop to celebrate little things for too long. There's always some new thing that needs to get done. Am I learning and improving? I think so, albeit slowly. Well, it seems slow to me. I'm getting used to presenting my ideas and research in readable and understandable ways. I'm getting used to the process of thinking about a problem and all the possible ways to tackle it. I'm also able to synthesize and hold multiple people's ideas in my mind at once, understanding each person's perspective. I'm able to be biased--yeah, it's actually a good thing. There was a time when I had no opinion, and even today, I'm still easily swayed, but I'm sticking to ideas that seem to make logical sense to me. Also, I'm aware that any idea I feel is logical really comes from other people anyway. Ultimately I don't have opinions of my own. </p><p>But that goes with everything. I realize that I am purely a product of my environment (nurture/nature argument). I just happen to be attracted to less mainstream ideas--in non-work aspects of life. When it comes to work, I tend to be mainstream but on the edgier side of technology.</p><p>It's been chillier here the past two days. I'm all pouty about it, too. It went up to 77 degrees yesterday. That's way too cold for summer. It needs to heat back up again.</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>