<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-08-24:/2006/08/binaural-sounds"; ?>
		<div class="publishedentry">
			<h2>Binaural Sounds</h2>
			<h3>24 August 2006  @ 09:27</h3>
			<p>I did some more fiddling with sounds early this morning and discovered that my formula for the sine wave was wrong. I forgot to multiply by 2pi. Okay, so here are the sounds with the correct frequencies. They are wav files (no compression) at 44100 samples per second. The best quality!</p><p><ul><br /><li><a href="http://iam.solostyle.net/snd/binaural_100_110.wav">100 Hz and 110 Hz</a></p><p>This is a pretty low sound. You could achieve the same beat frequency with two sounds at 500 Hz and 510 Hz, or even 2000 Hz and 2010 Hz, but the lower the pitch the more soothing. It seems like if the brain operates at very low frequencies (like 10 Hz) then a high pitched sound would counter the effect and possibly make you feel sick.</p><p></li><br /><li><a href="http://iam.solostyle.net/snd/binaural_100_110_1sfade.wav">100 Hz and 110 Hz with a fade every second</a></p><p>The idea with the fade was to see if one could align both the heart and the mind. Assuming that at rest, sitting upright, your heartrate is 60 beats a minute, or 1 per second, maybe making the sound fade in an out in a period of 1 second could help you harmonize your heart and your brain. </p><p></li><br /><li><a href="http://iam.solostyle.net/snd/binaural_200_210.wav">200 Hz and 210 Hz</a></p><p>Same as the first one, just an octave higher.</p><p></li><br /><li><a href="http://iam.solostyle.net/snd/binaural_75_81.wav">75 Hz and 81 Hz</a></p><p>The beat frequency here is lower, 6 Hz, or in the Theta stage. I wore headphones, turned the sound on to loop indefinitely, and fell asleep. Sort of. I was in a liminal half awake half asleep state. I think I might have fallen asleep and had strange dreams. When I woke up, I sort of had a headache. To be accurate, it felt painful to wake myself up, but once I was fully awake, there was no pain. And it was painful to try to relax into sleep, but once I had completely relaxed I felt fine. Interesting. More trials are needed! If any of you try it, I would like to know how it affects you.</p><p></li><br /></ul></p><p>By the way, I had the volume turned down to about 22% or less. I could still hear it, but the lower the volume, the less intruding.</p><p>Also, it would probably be more beneficial to have the sound slowly migrate from one brainwave stage to another. From a lower Beta (you should already be somewhat relaxed) to Alpha and finally to Theta. I don't think Delta is as useful for me because I don't have sleep problems. The <a href="http://www.bwgen.com">brainwave generator site</a> has the generator plus presets and custom user-created presets that do this very migration.</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>