<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-08-07:/2006/08/packed-schedule"; ?>
		<div class="publishedentry">
			<h2>Packed schedule</h2>
			<h3>07 August 2006  @ 09:11</h3>
			<p><p>I need to work some things out. Hm.. First of all, tomorrow I have to travel for twelve hours to get to Toronto. It isn't so bad on the way back, because the Mrs has arranged a car to take me from Toronto to Buffalo. But then following that, I'm supposed to ride fifty miles from Kenosha to Jefferson, and the next day another 50 miles from Jefferson to Madison. But that's not what I'm worried about. I'm also applying--late--for a Fulbright fellowship that if I don't start on soon, I probably won't be able to win. There's so much planning still left. I need to figure out just exactly what I want to study.</p><br /><p>So the pressure is on. Today I'm going to read the rest of the articles by Catherine Lewis on the subject of lesson study, but then I need to find more articles on things like student satisfaction and the life of teenagers in most places (not just the big cities). I am not going to be placed in Tokyo, anyway, so I should try to learn as much as I can about smaller town schools.</p><br /><p>Then for tomorrow's long trip, I need to pack some food. Let's see, what do I need to take with me?</p><br /><ol><br /><li>Messenger Bag</li><br /><li>Passport</li><br /><li>Cash for train, food, emergency cab</li><br /><li>Phone  -&- charger</li><br /><li>Wallet</li><br /><li>Water</li><br /><li>Food:<br /><ul><br /><li>Not as perishable</li><br /><li>Easy to prepare</li><br /><li>Easy to digest</li><br /></ul><br /></li><br /><li>Napkins</li><br /><li>Clothes:<br /><ul><br /><li>2 pairs of undies</li><br /><li>2 clean tops</li><br /><li>2 clean bottoms</li><br /><li>sweater</li><br /></ul><br /></li><br /><li>Toothbrush</li><br /><li>Fulbright-related articles</li><br /></ol><br /><p>I think I might just take a jar of peanut butter, some apples, and some bread. That just might be good enough. As for vegetables, well I'll just hope that apples have enough fiber and nutrients. All right, maybe some carrots and spinach, too, but I'll be eating them raw. The apples will be a bit heavy in my bag, but I am not taking a lot of excess stuff. Traveling light is the way to go. I'm glad I don't have an iPod or a camera or other electronic bores.</p><br /><p>I have to email my FFA to see when we can meet. If we can meet on Friday, when I get back from Toronto, then I can't do the ride to Madison. This Fulbright is more important than riding to Madison. And yes, my summer is also important, but actually this opportunity is far more important than my summer. And anyway my summer has been going well.</p><br /><p>Okay, well I'm going to get some work done. I might need to take the Metra downtown, even though it costs more, and then the Orange Line out to Midway, all in order to sleep a bit more in my lovely bed. The schedules need to match up, though. That's important.</p></p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>