<?		session_start();
	include '../../235/func.php';
	include '../../235/storevars.php';
	include '../../inc/header.php';?><? $_SESSION['entry_id'] = "tag:iam.solostyle.net,2006-09-05:/2006/09/eck"; ?>
		<div class="publishedentry">
			<h2>?Ec!k</h2>
			<h3>05 September 2006  @ 11:15</h3>
			<p>The hunger pangs seem to have abated now. According to someone on a forum, the difference between fasting and starving is that starving requires eating more.</p><p>Fasting is a complete denial of all food intake (except for a bit of water), but starving is eating a little each day. Fascinating.</p><p>I ate a lot last night and didn't feel hungry this morning when I awoke. I ran a few miles and lifted weights. It was a quick 1.5 hr workout and not terribly intense. I felt hunger pangs right after, and instinctively wanted to eat. I suppressed that desire by thinking about other things.</p><p>Then I remembered that torn muscles crave glycogen immediately after a workout, and the chance for muscle recovery greatly reduces after 30 minutes of working out. Well. It's been a couple of hours now, and I still refuse to eat. Food is so disgusting the way I have been eating it. I want to truly appreciate every morsel.</p><p>Why this self-denial? It's not just with food, it's with people, with feelings, with undeniable truths. In my high school years I allowed my feelings to dictate decisions. Feelings and thoughts were united and I just went with my gut. There was no real decision process. Anything I did originated from truth.</p><p>I know this. I know how to return to this. But now I feel like messing with it. For the past few years I've been pushing my mind and body to limits that I decide for myself.. and when I have the energy to endure it. It isn't stress in the usual sense of the world. There is no external stressor--it's all from within me. I pwnz it.</p><p>It's a little training, I suppose. I know that I'm bitter about love. I know that I'm still in love. Somewhere, I guess. I mean, I felt it last night so it must still be there. Just like I felt hunger a few hours ago, and I know that's still there. I just can't feel either hunger.</p><p>I choose freedom over hunger. I refuse to sate either--No. It's not that I refuse--neither hunger can be sated. Mark my words. If this raw physical hunger symbolizes a deeper spiritual hunger, I have already found the answer. The question and the answer are the same. The answer is <em>inside</em> the question.</p><p>Wow, my head feels so light and clear. I'm dressed in white today. My head is shaved. My stomach is empty. The water I sip is flushing my body of toxins. I can feel the areas of my head where heat escapes the most, because those areas are the more sensitive to air.</p><p><h3>So, what's up</h3></p><p>I am excited about today. I meet with Misako Hasebe-sama in half an hour here at Norris. We will exchange English and Japanese conversation. Then I go to a movie with Paul, another dear one. Every paul I know is so dear and sweet. And chaste. It's a bright clear day, so I get to bike down there! I'm sure that will make me hungrier, but I will be awake. Aware. Today I will know.</p>
			<div style="clear:both; padding-bottom: 0.25em;"></div>
			<p>
				<em><a name="bot" href="http://iam.solostyle.net/comment.php">comments</a></em>
			</p>
		</div>
	<?	include '../../comment.html';
	include '../../right.php';
	include '../../inc/footer.php';	?>